const constants = {

    'URL_PRODUCT_LIST': 'https://api.johnlewis.com/search/api/rest/v2/catalog/products/search/keyword?q=dishwasher&key=AIzaSyDD_6O5gUgC4tRW5f9kxC0_76XRC8W7_mI',
    'URL_PRODUCT_DESC': 'https://api.johnlewis.com/mobile-apps/api/v1/products/',

    'allMockProducts': [{
      "productId": "4131599",
      "type": "product",
      "title": "Bosch Serie 4 SMS46MI01G Freestanding Dishwasher, Grey",
      "htmlTitle": "",
      "code": "81701202",
      "averageRating": 4.7,
      "reviews": 22,
      "price": {
        "was": "",
        "then1": "",
        "then2": "",
        "now": "529.00",
        "uom": "",
        "currency": "GBP"
      },
      "image": "//johnlewis.scene7.com/is/image/JohnLewis/238008957?",
      "displaySpecialOffer": "",
      "promoMessages": {
        "reducedToClear": false,
        "priceMatched": "",
        "offer": "",
        "customPromotionalMessage": "",
        "bundleHeadline": "",
        "customSpecialOffer": {}
      },
      "nonPromoMessage": "",
      "defaultSkuId": "238008957",
      "colorSwatches": [{
        "color": "",
        "basicColor": "Grey",
        "colorSwatchUrl": "//johnlewis.scene7.com/is/image/JohnLewis/238008957?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
        "imageUrl": "//johnlewis.scene7.com/is/image/JohnLewis/238008957?",
        "isAvailable": true,
        "skuId": "238008957"
      }],
      "colorSwatchSelected": 0,
      "colorWheelMessage": "",
      "outOfStock": false,
      "emailMeWhenAvailable": false,
      "availabilityMessage": "",
      "compare": true,
      "fabric": "",
      "swatchAvailable": false,
      "categoryQuickViewEnabled": false,
      "swatchCategoryType": "",
      "brand": "Bosch",
      "ageRestriction": 0,
      "isInStoreOnly": false,
      "isMadeToMeasure": false,
      "isBundle": false,
      "isProductSet": false,
      "promotionalFeatures": [],
      "features": [],
      "dynamicAttributes": {
        "dishwashersize": "Full",
        "cutlerybasket": "Tray",
        "amperage": "10A",
        "integratedorfreestanding": "Freestanding",
        "weight": "49.8kg",
        "quietmark": "NO",
        "slimdepth": "NO",
        "placesettings": "14"
      },
      "directorate": "Technology Directora",
      "futureRelease": false,
      "multiSku": false,
      "fabricByLength": false,
      "quickAddToBasket": {
        "showPermanentOos": false,
        "showMoreInfoRedirectPDP": false,
        "simpleAddToBasket": true,
        "simpleMobileEmailMe": false,
        "showEmailMeTriggerQV": false,
        "showChooseSizeTriggerQV": false
      },
      "permanentOos": false
    }, {
      "productId": "4215447",
      "type": "product",
      "title": "Bosch Serie 4 SMV46JX01G Fully Integrated Dishwasher",
      "htmlTitle": "",
      "code": "88701206",
      "averageRating": 4.4,
      "reviews": 61,
      "price": {
        "was": "",
        "then1": "",
        "then2": "",
        "now": "549.00",
        "uom": "",
        "currency": "GBP"
      },
      "image": "//johnlewis.scene7.com/is/image/JohnLewis/238078364?",
      "displaySpecialOffer": "",
      "promoMessages": {
        "reducedToClear": false,
        "priceMatched": "",
        "offer": "",
        "customPromotionalMessage": "",
        "bundleHeadline": "",
        "customSpecialOffer": {}
      },
      "nonPromoMessage": "",
      "defaultSkuId": "238078364",
      "colorSwatches": [{
        "color": "",
        "basicColor": "Metallics",
        "colorSwatchUrl": "//johnlewis.scene7.com/is/image/JohnLewis/238078364?cropN=0.40421052631578946,0.5873684210526315,0.16842105263157894,0.16842105263157894&",
        "imageUrl": "//johnlewis.scene7.com/is/image/JohnLewis/238078364?",
        "isAvailable": true,
        "skuId": "238078364"
      }],
      "colorSwatchSelected": 0,
      "colorWheelMessage": "",
      "outOfStock": false,
      "emailMeWhenAvailable": false,
      "availabilityMessage": "",
      "compare": true,
      "fabric": "",
      "swatchAvailable": false,
      "categoryQuickViewEnabled": false,
      "swatchCategoryType": "",
      "brand": "Bosch",
      "ageRestriction": 0,
      "isInStoreOnly": false,
      "isMadeToMeasure": false,
      "isBundle": false,
      "isProductSet": false,
      "promotionalFeatures": [],
      "features": [],
      "dynamicAttributes": {
        "dishwashersize": "Full",
        "cutlerybasket": "Basket",
        "amperage": "10A",
        "integratedorfreestanding": "Integrated",
        "weight": "33.23kg",
        "quietmark": "NO",
        "slimdepth": "NO",
        "placesettings": "13"
      },
      "directorate": "Technology Directora",
      "futureRelease": false,
      "multiSku": false,
      "fabricByLength": false,
      "quickAddToBasket": {
        "showPermanentOos": false,
        "showMoreInfoRedirectPDP": false,
        "simpleAddToBasket": true,
        "simpleMobileEmailMe": false,
        "showEmailMeTriggerQV": false,
        "showChooseSizeTriggerQV": false
      },
      "permanentOos": false
    }, {
      "productId": "4189551",
      "type": "product",
      "title": "Siemens iQ300 SN236W03MG Freestanding Dishwasher, White",
      "htmlTitle": "",
      "code": "81701602",
      "averageRating": 4.7,
      "reviews": 18,
      "price": {
        "was": "",
        "then1": "",
        "then2": "",
        "now": "549.00",
        "uom": "",
        "currency": "GBP"
      },
      "image": "//johnlewis.scene7.com/is/image/JohnLewis/238008972?",
      "displaySpecialOffer": "",
      "promoMessages": {
        "reducedToClear": false,
        "priceMatched": "",
        "offer": "",
        "customPromotionalMessage": "",
        "bundleHeadline": "",
        "customSpecialOffer": {}
      },
      "nonPromoMessage": "",
      "defaultSkuId": "238008972",
      "colorSwatches": [{
        "color": "",
        "basicColor": "White",
        "colorSwatchUrl": "//johnlewis.scene7.com/is/image/JohnLewis/238008972?cropN=0.4054621848739496,0.5840336134453782,0.19117647058823528,0.19117647058823528&",
        "imageUrl": "//johnlewis.scene7.com/is/image/JohnLewis/238008972?",
        "isAvailable": true,
        "skuId": "238008972"
      }],
      "colorSwatchSelected": 0,
      "colorWheelMessage": "",
      "outOfStock": false,
      "emailMeWhenAvailable": false,
      "availabilityMessage": "",
      "compare": true,
      "fabric": "",
      "swatchAvailable": false,
      "categoryQuickViewEnabled": false,
      "swatchCategoryType": "",
      "brand": "Siemens",
      "ageRestriction": 0,
      "isInStoreOnly": false,
      "isMadeToMeasure": false,
      "isBundle": false,
      "isProductSet": false,
      "promotionalFeatures": [],
      "features": [],
      "dynamicAttributes": {
        "dishwashersize": "Full",
        "cutlerybasket": "Tray",
        "amperage": "10A",
        "integratedorfreestanding": "Freestanding",
        "weight": "50.1kg",
        "quietmark": "NO",
        "slimdepth": "NO",
        "placesettings": "14"
      },
      "directorate": "Technology Directora",
      "futureRelease": false,
      "multiSku": false,
      "fabricByLength": false,
      "quickAddToBasket": {
        "showPermanentOos": false,
        "showMoreInfoRedirectPDP": false,
        "simpleAddToBasket": true,
        "simpleMobileEmailMe": false,
        "showEmailMeTriggerQV": false,
        "showChooseSizeTriggerQV": false
      },
      "permanentOos": false
    }
    ]
};

export default constants;
